openapi: "3.0.0"
info:
  title: "Bookshelf API Documentation"
  version: "1.0.0"
  description: "Introducing Bookshelf API: Explore, Collect, Share. Your go-to for storing and sharing your favorite books."
  contact:
    name: "Gorgees Odisho"
    url: "https://gorgees.vercel.app/"
servers:
  - url: "http://localhost:3000/api"

# tages
tags:
  - name: "public books"

# paths
paths:
  # 1) /books
  /books/public:
    get:
      tags:
        - "public books"
      summary: "Get all public books + pagination"
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: number of limit of books to show
        - in: query
          name: offset
          schema:
            type: integer
          description: number of page (limit * offset)
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  book_id:
                    type: "string"
                  book_name:
                    type: "string"
                  description:
                    type: "string"
                  book_url:
                    type: "string"
                  file_path:
                    type: "string"
                  status:
                    type: "string"
                  author_name:
                    type: "string"
                  genre:
                    type: "string"
                  user:
                    type: "object"
                    properties:
                      user_id:
                        type: "string"
                      first_name:
                        type: "string"
                      last_name:
                        type: "string"
                      email:
                        type: "string"

  /books/public/{bookId}:
    get:
      tags:
        - "public books"
      summary: "Get single book by id"
      parameters:
        - in: path
          name: bookId
          required: true
          schema:
            type: string
          description: get a single book by book id
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  book_id:
                    type: "string"
                  book_name:
                    type: "string"
                  description:
                    type: "string"
                  book_url:
                    type: "string"
                  file_path:
                    type: "string"
                  status:
                    type: "string"
                  author_name:
                    type: "string"
                  genre:
                    type: "string"
                  user:
                    type: "object"
                    properties:
                      user_id:
                        type: "string"
                      first_name:
                        type: "string"
                      last_name:
                        type: "string"
                      email:
                        type: "string"

  # public books search
  /books/public/search:
    get:
      tags:
        - "public books"
      summary: "search for public books (book name or author name) + pagination"
      parameters:
        - in: query
          name: bookOrAuthor
          schema:
            type: string
          description: search for book by book name or author name
        - in: query
          name: limit
          schema:
            type: integer
          description: number of limit of books to show
        - in: query
          name: offset
          schema:
            type: integer
          description: number of page (limit * offset)
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  book_id:
                    type: "string"
                  book_name:
                    type: "string"
                  description:
                    type: "string"
                  book_url:
                    type: "string"
                  file_path:
                    type: "string"
                  status:
                    type: "string"
                  author_name:
                    type: "string"
                  genre:
                    type: "string"
                  user:
                    type: "object"
                    properties:
                      user_id:
                        type: "string"
                      first_name:
                        type: "string"
                      last_name:
                        type: "string"
                      email:
                        type: "string"

  # public books filter
  /books/public/filter:
    get:
      tags:
        - "public books"
      summary: "filter public books by genres + pagination"
      parameters:
        - in: query
          name: genres
          schema:
            type: string
          description: filter by genres
        - in: query
          name: limit
          schema:
            type: integer
          description: number of limit of books to show
        - in: query
          name: offset
          schema:
            type: integer
          description: number of page (limit * offset)
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  book_id:
                    type: "string"
                  book_name:
                    type: "string"
                  description:
                    type: "string"
                  book_url:
                    type: "string"
                  file_path:
                    type: "string"
                  status:
                    type: "string"
                  author_name:
                    type: "string"
                  genre:
                    type: "string"
                  user:
                    type: "object"
                    properties:
                      user_id:
                        type: "string"
                      first_name:
                        type: "string"
                      last_name:
                        type: "string"
                      email:
                        type: "string"
